### ISSUE TITLE
Transaction History Not Populating Correctly (#!account)

### ISSUE THREAD

**Issue by englishcoder** [ConcealNetwork/conceal-web-wallet#42]
OS: 
Microsoft Windows [Version 10.0.19044.1526]

Browser:
[Private Tab]
Brave: Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)

URL: 
https://wallet.conceal.network/#account

Issue:
Send/Receive multiple iterations and not populating

Vocabulary:
CWW = https://wallet.conceal.network/
Hub = https://app.conceal.network/wallets/

Details:
- Sent and received between CWW and Hub and although Hub is populating transactions and some did show up in CWW transaction history they disappeared with a few minutes and never reappeared.
- Waited until 10 confirmations on all transactions before opening ticket. 
- Did perform disconnect and "Reload my wallet", no change.
- https://wallet.conceal.network/#!settings did show correct "Current scanning height"
- Hub1 is transaction history from Hub
- CWW1 is transaction history from CWW
- CWW2 is transaction history from CWW *after* importing again from Mnemonic

Hub1
![Hub1](https://user-images.githubusercontent.com/29473008/155581086-cc4f2af2-4fc3-4523-be8f-1a41b2c147ad.jpg)

CWW1
![CWW1](https://user-images.githubusercontent.com/29473008/155581088-c5b39482-a743-4cf5-b8e0-2a13db548fbd.jpg)

CWW2
![CWW2](https://user-images.githubusercontent.com/29473008/155581080-f45e1ab3-8ba9-4641-ba91-db66d3d48bd5.jpg)

**Comment by krypt0x** [comment]
This issue has been sorted out! Thank you
