### ISSUE TITLE
I didn't receive my CCX from HeroMiners to web wallet 

### ISSUE THREAD

**Issue by marto993** [ConcealNetwork/conceal-web-wallet#85]
Hi!. I create this web wallet to receive the payments from mining pool.
![image](https://user-images.githubusercontent.com/99897420/236491324-629fafcd-385a-4cc1-8877-ac9d2b906af1.png)

but still don't seeing the funds in my balance
![image](https://user-images.githubusercontent.com/99897420/236491908-769c8f21-962d-43b7-bf54-90b814a16f96.png)

I'm doing anything wrong?

**Comment by ThrownLemon** [comment]
> 

Can you try using the desktop wallet? 
Just need to download here -> [Desktop Wallet](https://github.com/ConcealNetwork/conceal-desktop/releases/latest)

Just export your keys from the web wallet and import them into the desktop wallet and let it sync which can take a few hours to a day's depending on your internet.

Let us know if it doesn't show up.

**Comment by krypt0x** [comment]
thread closed for inactivity
